travis:
  secure:
    BINSTAR_TOKEN: RqSr4pwaQFGkiEYVMbp5Btb6LIKcrHryPXS/uNpunchWB3Ea0WDhM0tzBNuEmbU6njI9Qgd3dUW+Z70GvPJDK+bZXaa9jjd9P/CGCDrS1M7UBjeE4Ahr28D1yx4jtD//XbuLC7OT5DuX+891k3fJDsdEqQMxt9P6ixU6Vk0UKgnLMrGdxS3RE8Ur1RZcW2AXr4zZ9w02uZEYT4ODW/Fi/XqhIMWvssDNqsqVpiMhN8IgPiWm6yNdJU9a1Sq4RSEd4jaLruBAv6zbfSaElMg5ptGgj3P2Qh4ATOGr0fQaxItWQu+YszNL4xEjk6/Amc18n8YYgUVLkGCZZGXChYJNOK/HEevogDKLtow8/xsUqz3CUWcLPZLvjqmBv069yECxiU4AnzkWhgBCdvXJpt6YaX50NWVO7Hm3xwtUN2zcsCm9BgpLRBVHiTa/aaNKcZHkdwZTFXZ2/BpFG9mY0pbf7BwAfX4y8sw4Fp0hVKK5kOMOdOU+Rld2zWKsemj1+dL9wpHJL2PzoogEX4EW3uZ+BrIIGYEEwAppbo9bKtnhA/KdM/pN+Ng4VLVClRXOyhvUAvdlfTyuKNWkU3co0Dh8DFdCun6+dk5lHgn3L4IZLQhWc5xHe8eNWbrJCkLeKEe00RwGFgnRiuMIxAD5BDzcAxiZvlIin95HcqAC8wbFMY0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
