travis:
  secure:
    BINSTAR_TOKEN: pAUFE9Fd6Xa0fDWeXOAwd0ESrJP3/FqWrJB2Pc+WB8mmiVj/kqJXL9SVd2GixZ67QehcBJ80J23n005KHwDVuyBMcSphkUxADebdsW0nqTBdKMSw4/zqednRXFxsp7qukJSYOK1nygHzfKj69Jt3C1mSdxlfcpUfm46SAg68LY9gT0CMsSDTJxyELXWdYXSWlZdivg1d+mhC0i/w+n8rnHPxV96cxET0yztN+q8NdnZnXE0X0sbJ82/5EDwqG9/fg6Z1u/OSYSGvGJuR4fQTFRhiFpSZHgzU9iWXZS9EFAhXcIMCHoN2CmY6u7f9hhwy9MZ23rnH0byEMTQXJVKaWKBrFT+Hvgj6O4jHBIxkBbdOti45QmkwLEOqFyw6i++HEoTfiz4h0eff74N0y76cEf64ARAhvhJPN3fOxBMeIWnpz5Yp3V9I7QSnW8jOsMJApVZtWc7f+mjgLi33H5WIEKDnuWfMU27Su86KboQ0ruQ+WHLQ2X/HG29Vv6Nk7bmCtbejY/cWkE4suoxphxq2gbkA8FClnnqal6HSVTzUYnUYS9PBIXpQ2rzeTMJKQVT6JuX7GHKsXF+GO2iJvpnWoM0/VMLKY4ogTg5lDAfYElgy9nGjeJ+W8tRZloTmzL29hSfbV9LuyJAhFpuA9lc8X7vvYWyIk/3KgtkH7egCeFQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
